FROM python:3.12-slim

WORKDIR /app

COPY frontend/ frontend/
COPY data/ data/
COPY .env .env

RUN pip install --no-cache-dir -r frontend/requirements.txt

EXPOSE 5000

CMD ["python", "frontend/app.py"]
