services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile.middleware
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    env_file: .env
    networks:
      - crisis-net
      - easypanel-hktn2k26
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      - API_URL=http://middleware:8000
    depends_on:
      - middleware
    networks:
      - crisis-net
      - easypanel-hktn2k26
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crisis-frontend.rule=Host(`hackathon.albuqr.com`)"
      - "traefik.http.routers.crisis-frontend.entrypoints=websecure"
      - "traefik.http.routers.crisis-frontend.tls=true"
      - "traefik.http.routers.crisis-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.crisis-frontend.loadbalancer.server.port=5000"
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./data:/app/data
    env_file: .env
    environment:
      - API_URL=http://middleware:8000
    depends_on:
      - middleware
    networks:
      - crisis-net
    restart: always

networks:
  crisis-net:
    driver: bridge
  easypanel-hktn2k26:
    external: true
